from __future__ import annotations

import argparse
import importlib.metadata
import secrets
import shutil
import subprocess
import sys
import textwrap
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Mapping, Sequence


DEFAULT_INSTALL_DIR = Path.home() / ".novwr"
DEFAULT_IMAGE = "ghcr.io/hurricane0698/novelwriter:latest"
DEFAULT_BIND_HOST = "127.0.0.1"
DEFAULT_PORT = "8000"
DEFAULT_DATA_DIR = "./data"
DEFAULT_CONTAINER_NAME = "novwr"
DEFAULT_OPENAI_BASE_URL = "https://api.openai.com/v1"
DEFAULT_OPENAI_MODEL = "gpt-4o-mini"
DEFAULT_JWT_PLACEHOLDER = "CHANGE-ME-IN-PRODUCTION"
COMPOSE_FILE_NAME = "docker-compose.yml"
ENV_FILE_NAME = ".env"


def _project_version() -> str:
    try:
        return importlib.metadata.version("novwr")
    except importlib.metadata.PackageNotFoundError:
        return "0.1.0"


def resolve_install_dir(path: str | None) -> Path:
    return Path(path).expanduser().resolve() if path else DEFAULT_INSTALL_DIR.resolve()


def default_env_values() -> dict[str, str]:
    return {
        "NOVWR_IMAGE": DEFAULT_IMAGE,
        "NOVWR_BIND_HOST": DEFAULT_BIND_HOST,
        "NOVWR_PORT": DEFAULT_PORT,
        "NOVWR_DATA_DIR": DEFAULT_DATA_DIR,
        "NOVWR_CONTAINER_NAME": DEFAULT_CONTAINER_NAME,
        "OPENAI_API_KEY": "",
        "OPENAI_BASE_URL": DEFAULT_OPENAI_BASE_URL,
        "OPENAI_MODEL": DEFAULT_OPENAI_MODEL,
        "JWT_SECRET_KEY": secrets.token_urlsafe(48),
        "DEPLOY_MODE": "selfhost",
        "ENVIRONMENT": "dev",
        "DATABASE_URL": "sqlite:////data/scngs.db",
        "SCNGS_DATA_DIR": "/data",
    }


def docker_compose_template() -> str:
    return textwrap.dedent(
        """\
        services:
          novwr:
            image: ${NOVWR_IMAGE}
            container_name: ${NOVWR_CONTAINER_NAME}
            restart: unless-stopped
            ports:
              - "${NOVWR_BIND_HOST}:${NOVWR_PORT}:8000"
            env_file:
              - .env
            volumes:
              - ${NOVWR_DATA_DIR}:/data
        """
    )


def parse_env_file(text: str) -> dict[str, str]:
    env: dict[str, str] = {}
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        env[key.strip()] = value.strip()
    return env


def build_env_file(
    existing: Mapping[str, str] | None = None,
    *,
    image: str | None = None,
    bind_host: str | None = None,
    port: str | None = None,
) -> str:
    merged = default_env_values()
    if existing:
        merged.update(existing)
    if image is not None:
        merged["NOVWR_IMAGE"] = image
    if bind_host is not None:
        merged["NOVWR_BIND_HOST"] = bind_host
    if port is not None:
        merged["NOVWR_PORT"] = str(port)
    if not merged.get("JWT_SECRET_KEY"):
        merged["JWT_SECRET_KEY"] = secrets.token_urlsafe(48)

    ordered_keys = [
        "NOVWR_IMAGE",
        "NOVWR_BIND_HOST",
        "NOVWR_PORT",
        "NOVWR_DATA_DIR",
        "NOVWR_CONTAINER_NAME",
        "OPENAI_API_KEY",
        "OPENAI_BASE_URL",
        "OPENAI_MODEL",
        "JWT_SECRET_KEY",
        "DEPLOY_MODE",
        "ENVIRONMENT",
        "DATABASE_URL",
        "SCNGS_DATA_DIR",
    ]

    lines = [
        "# Generated by novwr CLI.",
        "# Edit OPENAI_API_KEY (and optionally OPENAI_BASE_URL / OPENAI_MODEL) before serious use.",
        "",
    ]
    extra_keys = sorted(key for key in merged if key not in ordered_keys)
    for key in [*ordered_keys, *extra_keys]:
        lines.append(f"{key}={merged[key]}")
    lines.append("")
    return "\n".join(lines)


def ensure_install_scaffold(
    install_dir: Path,
    *,
    force: bool = False,
    image: str | None = None,
    bind_host: str | None = None,
    port: str | None = None,
) -> dict[str, str]:
    install_dir.mkdir(parents=True, exist_ok=True)
    compose_path = install_dir / COMPOSE_FILE_NAME
    env_path = install_dir / ENV_FILE_NAME

    existing_env = parse_env_file(env_path.read_text(encoding="utf-8")) if env_path.exists() else {}
    env_text = build_env_file(
        existing_env,
        image=image,
        bind_host=bind_host,
        port=port,
    )
    env_values = parse_env_file(env_text)

    if force or not compose_path.exists():
        compose_path.write_text(docker_compose_template(), encoding="utf-8")

    if force or not env_path.exists() or existing_env != env_values:
        env_path.write_text(env_text, encoding="utf-8")

    data_path = resolve_data_dir(install_dir, env_values)
    data_path.mkdir(parents=True, exist_ok=True)
    return env_values


def resolve_data_dir(install_dir: Path, env: Mapping[str, str]) -> Path:
    configured = env.get("NOVWR_DATA_DIR", DEFAULT_DATA_DIR)
    data_path = Path(configured).expanduser()
    if data_path.is_absolute():
        return data_path
    return (install_dir / data_path).resolve()


def healthcheck_url_for_env(env: Mapping[str, str]) -> str:
    host = env.get("NOVWR_BIND_HOST", DEFAULT_BIND_HOST).strip() or DEFAULT_BIND_HOST
    if host in {"0.0.0.0", "::", "[::]"}:
        host = "127.0.0.1"
    port = env.get("NOVWR_PORT", DEFAULT_PORT).strip() or DEFAULT_PORT
    return f"http://{host}:{port}/api/health"


def _run(
    command: Sequence[str],
    *,
    cwd: Path | None = None,
    capture_output: bool = False,
    check: bool = False,
) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        list(command),
        cwd=str(cwd) if cwd else None,
        capture_output=capture_output,
        text=True,
        check=check,
    )


def detect_compose_command() -> list[str] | None:
    for candidate in (["docker", "compose"], ["docker-compose"]):
        try:
            completed = _run([*candidate, "version"], capture_output=True)
        except FileNotFoundError:
            continue
        if completed.returncode == 0:
            return candidate
    return None


def require_compose_command() -> list[str]:
    command = detect_compose_command()
    if command is None:
        raise RuntimeError(
            "Docker Compose is not available. Install Docker Desktop or docker + compose plugin first."
        )
    return command


def wait_for_health(url: str, *, timeout_seconds: int = 45) -> dict[str, object]:
    deadline = time.time() + timeout_seconds
    last_error: str | None = None

    while time.time() < deadline:
        try:
            with urllib.request.urlopen(url, timeout=3) as response:
                payload = response.read().decode("utf-8")
            if '"status"' in payload and '"healthy"' in payload:
                return {"ok": True, "payload": payload}
            last_error = f"Unexpected health payload: {payload}"
        except (urllib.error.URLError, TimeoutError, OSError) as exc:
            last_error = str(exc)
        time.sleep(1)

    raise RuntimeError(f"NovWr did not become healthy at {url}: {last_error or 'unknown error'}")


def _load_current_env(install_dir: Path) -> dict[str, str]:
    env_path = install_dir / ENV_FILE_NAME
    if not env_path.exists():
        raise RuntimeError(f"Missing {env_path}. Run `novwr init` first.")
    return parse_env_file(env_path.read_text(encoding="utf-8"))


def _safe_rmtree(path: Path, *, what: str) -> None:
    resolved = path.resolve()
    home = Path.home().resolve()
    if resolved in {Path("/"), home}:
        raise RuntimeError(f"Refusing to delete {what} at dangerous path: {resolved}")
    shutil.rmtree(resolved)


def cmd_init(args: argparse.Namespace) -> int:
    install_dir = resolve_install_dir(args.dir)
    env = ensure_install_scaffold(
        install_dir,
        force=args.force,
        image=args.image,
        bind_host=args.bind_host,
        port=args.port,
    )
    print(f"Initialized NovWr selfhost directory: {install_dir}")
    print(f"- Compose file: {install_dir / COMPOSE_FILE_NAME}")
    print(f"- Env file:     {install_dir / ENV_FILE_NAME}")
    print(f"- Data dir:     {resolve_data_dir(install_dir, env)}")
    print("Next: edit OPENAI_API_KEY if needed, then run `novwr run`.")
    return 0


def _deploy(install_dir: Path, *, pull: bool) -> dict[str, str]:
    env = _load_current_env(install_dir)
    compose = require_compose_command()

    try:
        docker_info = _run(["docker", "info"], capture_output=True)
    except FileNotFoundError as exc:
        raise RuntimeError("Docker is not installed or not on PATH.") from exc
    if docker_info.returncode != 0:
        raise RuntimeError("Docker daemon is not reachable. Start Docker first.")

    if pull:
        _run([*compose, "pull"], cwd=install_dir, check=True)
    _run([*compose, "up", "-d"], cwd=install_dir, check=True)

    health_url = healthcheck_url_for_env(env)
    wait_for_health(health_url)
    print(f"NovWr is running at {health_url.removesuffix('/api/health')}")
    if not env.get("OPENAI_API_KEY", "").strip():
        print("Warning: OPENAI_API_KEY is empty; configure it in .env before using AI generation.")
    return env


def cmd_run(args: argparse.Namespace) -> int:
    install_dir = resolve_install_dir(args.dir)
    if not (install_dir / ENV_FILE_NAME).exists():
        ensure_install_scaffold(
            install_dir,
            image=args.image,
            bind_host=args.bind_host,
            port=args.port,
        )
    _deploy(install_dir, pull=args.pull)
    return 0


def cmd_upgrade(args: argparse.Namespace) -> int:
    install_dir = resolve_install_dir(args.dir)
    current = _load_current_env(install_dir)
    env_text = build_env_file(
        current,
        image=args.image,
        bind_host=None,
        port=None,
    )
    (install_dir / ENV_FILE_NAME).write_text(env_text, encoding="utf-8")
    _deploy(install_dir, pull=True)
    return 0


def cmd_uninstall(args: argparse.Namespace) -> int:
    install_dir = resolve_install_dir(args.dir)
    env_path = install_dir / ENV_FILE_NAME
    compose_path = install_dir / COMPOSE_FILE_NAME
    env = parse_env_file(env_path.read_text(encoding="utf-8")) if env_path.exists() else {}
    data_dir = resolve_data_dir(install_dir, env) if env else (install_dir / "data").resolve()

    compose = detect_compose_command()
    if compose is not None and compose_path.exists():
        _run([*compose, "down", "--remove-orphans"], cwd=install_dir, check=True)
        print("Stopped and removed the NovWr Docker stack.")
    elif compose_path.exists():
        print("Warning: Docker Compose not available; skipping `compose down` and only cleaning local files.")

    for managed_path in (compose_path, env_path):
        if managed_path.exists():
            managed_path.unlink()
            print(f"Removed {managed_path}")

    if args.delete_data and data_dir.exists():
        _safe_rmtree(data_dir, what="NovWr data directory")
        print(f"Removed data directory: {data_dir}")
    elif data_dir.exists():
        print(f"Preserved data directory: {data_dir}")
        print("Re-run with `novwr uninstall --delete-data` if you also want to delete local data.")

    if install_dir.exists() and not any(install_dir.iterdir()):
        install_dir.rmdir()
        print(f"Removed empty install directory: {install_dir}")
    elif install_dir.exists():
        print(f"Install directory still present: {install_dir}")

    return 0


def cmd_doctor(args: argparse.Namespace) -> int:
    install_dir = resolve_install_dir(args.dir)
    failed = False

    def ok(message: str) -> None:
        print(f"[ok]   {message}")

    def warn(message: str) -> None:
        print(f"[warn] {message}")

    def fail(message: str) -> None:
        nonlocal failed
        failed = True
        print(f"[fail] {message}")

    compose = detect_compose_command()
    if compose is None:
        fail("Docker Compose not found (`docker compose` or `docker-compose`).")
    else:
        ok(f"Docker Compose available via: {' '.join(compose)}")

    try:
        docker_info = _run(["docker", "info"], capture_output=True)
    except FileNotFoundError:
        fail("Docker CLI not found on PATH.")
        docker_info = None
    if docker_info is not None:
        if docker_info.returncode == 0:
            ok("Docker daemon is reachable.")
        else:
            fail("Docker daemon is not reachable.")

    compose_path = install_dir / COMPOSE_FILE_NAME
    env_path = install_dir / ENV_FILE_NAME
    if compose_path.exists():
        ok(f"Compose file present: {compose_path}")
    else:
        fail(f"Missing compose file: {compose_path}")

    if env_path.exists():
        ok(f"Env file present: {env_path}")
        env = parse_env_file(env_path.read_text(encoding="utf-8"))
    else:
        fail(f"Missing env file: {env_path}")
        env = {}

    if env:
        if env.get("JWT_SECRET_KEY", "").strip() and env["JWT_SECRET_KEY"] != DEFAULT_JWT_PLACEHOLDER:
            ok("JWT secret is configured.")
        else:
            fail("JWT secret is missing or still using the placeholder.")

        if env.get("OPENAI_API_KEY", "").strip():
            ok("OPENAI_API_KEY is configured.")
        else:
            warn("OPENAI_API_KEY is empty; AI generation will not work until configured.")

        data_dir = resolve_data_dir(install_dir, env)
        if data_dir.exists():
            ok(f"Data directory ready: {data_dir}")
        else:
            warn(f"Data directory does not exist yet: {data_dir}")

        health_url = healthcheck_url_for_env(env)
        try:
            wait_for_health(health_url, timeout_seconds=3)
        except RuntimeError as exc:
            warn(f"Healthcheck not ready: {exc}")
        else:
            ok(f"Healthcheck passed: {health_url}")

    if compose is not None and compose_path.exists() and env_path.exists():
        config = _run([*compose, "config"], cwd=install_dir, capture_output=True)
        if config.returncode == 0:
            ok("Docker Compose config resolves successfully.")
        else:
            fail("Docker Compose config failed to resolve.")

    return 1 if failed else 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="novwr",
        description="NovWr selfhost CLI for image-based one-click install and lifecycle management.",
    )
    parser.add_argument("--version", action="version", version=f"%(prog)s {_project_version()}")
    subparsers = parser.add_subparsers(dest="command", required=True)

    init_parser = subparsers.add_parser("init", help="Create or update the selfhost install scaffold.")
    init_parser.add_argument("--dir", help="Install directory. Defaults to ~/.novwr")
    init_parser.add_argument("--image", help=f"Override Docker image (default: {DEFAULT_IMAGE})")
    init_parser.add_argument("--bind-host", help=f"Override bind host (default: {DEFAULT_BIND_HOST})")
    init_parser.add_argument("--port", help=f"Override host port (default: {DEFAULT_PORT})")
    init_parser.add_argument("--force", action="store_true", help="Rewrite managed files even if they already exist.")
    init_parser.set_defaults(func=cmd_init)

    run_parser = subparsers.add_parser("run", help="Start the NovWr Docker stack.")
    run_parser.add_argument("--dir", help="Install directory. Defaults to ~/.novwr")
    run_parser.add_argument("--image", help=f"Override Docker image (default: {DEFAULT_IMAGE})")
    run_parser.add_argument("--bind-host", help=f"Override bind host (default: {DEFAULT_BIND_HOST})")
    run_parser.add_argument("--port", help=f"Override host port (default: {DEFAULT_PORT})")
    run_parser.add_argument("--pull", action="store_true", help="Pull the latest image before starting.")
    run_parser.set_defaults(func=cmd_run)

    doctor_parser = subparsers.add_parser("doctor", help="Inspect the local selfhost installation.")
    doctor_parser.add_argument("--dir", help="Install directory. Defaults to ~/.novwr")
    doctor_parser.set_defaults(func=cmd_doctor)

    upgrade_parser = subparsers.add_parser("upgrade", help="Pull and restart the latest configured image.")
    upgrade_parser.add_argument("--dir", help="Install directory. Defaults to ~/.novwr")
    upgrade_parser.add_argument("--image", help="Optionally replace NOVWR_IMAGE before upgrading.")
    upgrade_parser.set_defaults(func=cmd_upgrade)

    uninstall_parser = subparsers.add_parser(
        "uninstall",
        help="Remove the local NovWr selfhost install. Preserves data unless --delete-data is passed.",
    )
    uninstall_parser.add_argument("--dir", help="Install directory. Defaults to ~/.novwr")
    uninstall_parser.add_argument(
        "--delete-data",
        action="store_true",
        help="Also delete the local data directory resolved from NOVWR_DATA_DIR.",
    )
    uninstall_parser.set_defaults(func=cmd_uninstall)

    return parser


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        return int(args.func(args))
    except subprocess.CalledProcessError as exc:
        print(exc.stderr or str(exc), file=sys.stderr)
        return exc.returncode or 1
    except RuntimeError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1
    except KeyboardInterrupt:
        print("Interrupted.", file=sys.stderr)
        return 130


if __name__ == "__main__":
    raise SystemExit(main())
